src/Entity/Panier.php
<?php

namespace App\Entity;

use App\Repository\PanierRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: PanierRepository::class)]
class Panier
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'panier', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Utilisateur $Utilisateur = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    #[ORM\Datetime]
    private ?\DateTimeInterface $date_achat = null;

    #[ORM\Column]
    #[ORM\NotBlank]
    #[Assert\Type('boolean')]
    private ?bool $etat = null;

    #[ORM\OneToMany(mappedBy: 'panier', targetEntity: ContenuPanier::class, orphanRemoval: true)]
    private Collection $contenuPaniers;

    public function __construct()
    {
        $this->contenuPaniers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->Utilisateur;
    }

    public function setUtilisateur(Utilisateur $Utilisateur): self
    {
        $this->Utilisateur = $Utilisateur;

        return $this;
    }

    public function getDateAchat(): ?\DateTimeInterface
    {
        return $this->date_achat;
    }

    public function setDateAchat(?\DateTimeInterface $date_achat): self
    {
        $this->date_achat = $date_achat;

        return $this;
    }

    public function isEtat(): ?bool
    {
        return $this->etat;
    }

    public function setEtat(bool $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    /**
     * @return Collection<int, ContenuPanier>
     */
    public function getContenuPaniers(): Collection
    {
        return $this->contenuPaniers;
    }

    public function addContenuPanier(ContenuPanier $contenuPanier): self
    {
        if (!$this->contenuPaniers->contains($contenuPanier)) {
            $this->contenuPaniers->add($contenuPanier);
            $contenuPanier->setPanier($this);
        }

        return $this;
    }

    public function removeContenuPanier(ContenuPanier $contenuPanier): self
    {
        if ($this->contenuPaniers->removeElement($contenuPanier)) {
            // set the owning side to null (unless already changed)
            if ($contenuPanier->getPanier() === $this) {
                $contenuPanier->setPanier(null);
            }
        }

        return $this;
    }
}

src/Form/PanierType.php
<?php

namespace App\Form;

use App\Entity\Panier;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PanierType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add('etat');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Panier::class,
        ]);
    }
}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use Datetime;
use App\Entity\Panier;
use App\Form\PanierType;
use App\Repository\PanierRepository;
use App\Repository\ContenuPanierRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('{_locale}/panier')]
class PanierController extends AbstractController
{
    #[Route('/', name: 'app_panier_index', methods: ['GET'])]
    public function index(PanierRepository $panierRepository): Response
    {
        $user = $this->getUser();

        // Récupère les commandes de l'utilisateur connecté.
        return $this->render('panier/index.html.twig', [
            'paniers' => $panierRepository->findByEtatAndUtilisateur(1, $user),
            'utilisateur' => $user
        ]);
    }

    #[Route('/new', name: 'app_panier_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PanierRepository $panierRepository): Response
    {

        $panier = new Panier();
        $form = $this->createForm(PanierType::class, $panier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $panier->setUtilisateur($this->getUser());
            $panierRepository->save($panier, true);

            return $this->redirectToRoute('app_panier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('panier/new.html.twig', [
            'panier' => $panier,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_panier_show', methods: ['GET'])]
    public function show(Panier $panier): Response
    {
            //affiche le panier de l'utilisateur
        return $this->render('panier/show.html.twig', [
            'panier' => $panier,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_panier_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Panier $panier, PanierRepository $panierRepository): Response
    {

        $form = $this->createForm(PanierType::class, $panier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $panierRepository->save($panier, true);

            return $this->redirectToRoute('app_panier_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('panier/edit.html.twig', [
            'panier' => $panier,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_panier_delete', methods: ['POST'])]
    public function delete(Request $request, Panier $panier, PanierRepository $panierRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$panier->getId(), $request->request->get('_token'))) {
            $panierRepository->remove($panier, true);
        }

        return $this->redirectToRoute('app_panier_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/panier/_delete_form.html.twig
<form method="post" action="{{ path('app_panier_delete', {'id': panier.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ panier.id) }}">
    <button class="btn">{{ 'produit.supprimer'|trans }}</button>
</form>

templates/panier/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/panier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Panier{% endblock %}

{% block body %}
    <h1>Edit Panier</h1>

    {{ include('panier/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_panier_index') }}">back to list</a>

    {{ include('panier/_delete_form.html.twig') }}
{% endblock %}

templates/panier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'title.espace'|trans }}{% endblock %}

{% block body %}
    <h1 class="text text-center">{{ 'title.espace'|trans }}</h1>
    <br/>

    <h3>{{ 'title.histo'|trans }}</h3>
{{ include ("contenu_panier/list.html.twig", { contenu_paniers: paniers, super_admin: false, commande: true, display_action: false }) }}
    {{ include('utilisateur/show.html.twig', {'utilisateur': utilisateur}) }}    
{% endblock %}

templates/panier/list.html.twig
{% if paniers|length > 0 %}
    {% set montant = 0 %}
    <table class="table">
        <thead>
            <tr>
                {% if super_admin or commande %}
                    <th>Numéro</th>
                    {% if super_admin %}
                        <th>Utilisateur</th>
                    {% endif %}
                {% endif %}
                {% if commande is same as false %}
                    <th>Produits</th>
                {% endif %}
                <th>Montant total</th>
                {% if commande %}
                    <th>Date d'achat</th>
                {% endif %}
                {% if super_admin is same as false or (commande is same as true) %}
                    <th>Action</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for panier in paniers %}
                <tr>
            {% if super_admin  or commande %}
                <th>#{{ panier.id }}</th>
                {% if super_admin %}
                    <td>{{ panier.utilisateur.email }}</td>
                {% endif %}
            {% endif %}
            {% if commande is same as false %}
                <td class="col-md-2">
                    <ul>
                        {% for contenu in panier.contenuPaniers %}
                            <li>
                                <strong> 
                                    <span class="item-quantity"></span>{{contenu.produit.nom}} x {{ contenu.quantite }}
                                </strong>
                                <div class="price">{{ contenu.produit.prix }}EUR</div>
                            </li>
                        {% endfor %}
                    </ul>
                </td>
            {% endif %}
            <td>
                {% for contenu in panier.contenuPaniers %}
                    {% set montant = montant + (contenu.produit.prix * contenu.quantite) %}
                {% endfor %}
               {{ montant }}€
            </td>
            {% if commande %}
                <td>{{ panier.dateAchat ? panier.dateAchat|date("d/m/Y h:i:s") : '' }}</td>
            {% endif %}
            {% if (super_admin is same as false) or (commande is same as true) %}
                <td>
                    {% if panier.etat is same as true %}
                        <a class="btn btn-primary mr-2" href="{{ path('app_panier_show', {'id': panier.id}) }}">Voir la commande</a>
                    {% else %}
                            {{ include('panier/_delete_form.html.twig', {'id': panier.id}) }}
                    {% endif %}
                </td>
            {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    {% else %}
        {% if super_admin %}
            <p class="bg-warning text-center">Aucun panier en cours !</p>
        {% else %}
            <p class="text text-center">Vous n'avez aucune commande !</p>
        {% endif %}
    {% endif %}
</table>

templates/panier/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Panier{% endblock %}

{% block body %}
    <h1>Create new Panier</h1>

    {{ include('panier/_form.html.twig') }}

    <a href="{{ path('app_panier_index') }}">back to list</a>
{% endblock %}

templates/panier/show.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('/css/style3.css') }}">

    <style>
        .basket { width: 100% !important; }
    </style>
{% endblock %}

{% block title %}Panier{% endblock %}

{% block body %}
    <h1 class="text-center">Commande n°{{panier.id}}</h1>
    <h4 class="text-center">Payée le {{ panier.dateAchat ? panier.dateAchat|date('d/m/Y') : '' }}</h4>

    <p>
        <a class="btn-link" href="{{ path('app_panier_index') }}">Mon espace </a> > Historique des commandes > Commande n°{{ panier.id }}
    </p>
    <br/>
{{ include ("contenu_panier/list.html.twig", { contenu_paniers: panier.contenuPaniers, super_admin: false, commande: false, display_action: false }) }}
{% endblock %}